### ISSUE TITLE
Duration parameter does not work properly

### ISSUE THREAD

**Issue by rodrigoschaefer** [otonielduarte/gradient-progress-indicator#1]
When setting duration: 60 the animation completes a circle at about 45 seconds

**Comment by otonielduarte** [comment]
Hi @rodrigoschaefer , sorry for the delayed answer.

fixed the duration of the first animator and start the second animator after its finishes.

Thanks for using this package.

I'll close this issue for now, but feel free to reopen it with you need.

**Comment by rodrigoschaefer** [comment]
Hi @otonielduarte 
Tested latest version. The animation seems irregular. It starts really fast and slows down as it progresses. Is there a way to keep it at the same speed all the way?

**Comment by otonielduarte** [comment]
Hi @rodrigoschaefer 

The animation has that comportment because I was using the 'Curves.decelerate', I submitted a new version that you can change the animation curve. See the animations: https://api.flutter.dev/flutter/animation/Curves-class.html
